services:
  smart-mcp-proxy:
    container_name: smart-mcp-proxy
    image: ghcr.io/timthesinner/smart-mcp-proxy:latest
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MCP_PROXY_CONFIG=/app/config.json
    privileged: true