services:
  smart-mcp-proxy-dev:
    container_name: smart-mcp-proxy-dev
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "9090:8080"
    volumes:
      - ./config.json:/app/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GIN_MODE=debug
      - MCP_PROXY_CONFIG=/app/config.json
      - MCP_PROXY_MODE=http
    user: "${UID}:${GID}"
    privileged: true