name: CI/CD

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  fmt-and-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Run go fmt check
        run: |
          if ! go fmt ./... | tee /dev/stderr | grep -q '^'; then
            echo "Code is properly formatted"
          else
            echo "Code is not properly formatted. Please run 'go fmt ./...' to format your code."
            exit 1
          fi

      - name: Run go tests
        run: go test ./...

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: fmt-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/timthesinner/smart-mcp-proxy:latest
            ghcr.io/timthesinner/smart-mcp-proxy:${{ github.sha }}